### ISSUE TITLE
What changes should be made to z-nomp?

### ISSUE THREAD

**Issue by hardx4** [BTCGPU/BTCGPU#112]
Hello, what changes need to be made to z-nomp to work on the public test of November 1?

We've waited for this so long, can not you publish instructions?

**Comment by Coryvmcs1** [comment]
They will probably publish them after they launch them on pool.gold. This is a typical launch of potential scammish stuff. We have been waiting since day one to launch testnet and have been in the dark.

**Comment by StarbuckBG** [comment]
Because you stay and do nothing else than waiting to make money!
I got final touches on it. It will be available in 3 - 4 hours. I’m still testing it as I has problems with payment processing.
And when you are just staying and waiting for something, you have no right to complain, because I have spent totally less than 30 hours in the last week as you are just waiting …!

**Comment by virtualrobotix** [comment]
Hi StarBuckBG,
great job guys :) If you need suport to debug your work we are available :)
best
Roberto

**Comment by StarbuckBG** [comment]
@virtualrobotix Thanks!

**Comment by TheComputerGenie** [comment]
![commassavelives_newthumb](https://user-images.githubusercontent.com/21057518/32273823-0899ddec-bed2-11e7-8052-3c0afe7dfc96.png)

**Comment by StarbuckBG** [comment]
Check repo https://github.com/poolgold/z-nomp :)

**Comment by abakus1** [comment]
Hi. 
After I will make this changes , It will be possible to mine only btggold and the rest coin too or only btggold on this pool? Tonight I will test it.

**Comment by StarbuckBG** [comment]
Only bitcoin gold. Most of the equihash crypto currencies will improve to have the same protocol as BTG as it is better.

**Comment by abakus1** [comment]
Thx. Ok. I will try with new vps and test z-nomp with btgold.

**Comment by L1ND44U** [comment]
StarbuckBG people are waiting and Asking, no one care how much time you spent on it - it's your job - you are getting paid a lot of BTG and you can hack some BTG accounts to have some extra money later.

**Comment by StarbuckBG** [comment]
@L1ND44U
My job is to work as iOS Development Lead in a Bulgarian Startup, I also have few applications in the AppStore. The fact that I have decided to contribute to the projects don’t make it my job. If you contribute to the projects you will also get bounties and etc. And a note I’m not taking a lot of BTG, if I were I would probably be on the Hawaii right now, not coding 18 hours a day…
Your statement that someone could “hack” BTG account, is completely irrelevant. If it was possible then all of the crypto network developers will be the richest people in the world. Moreover I’m a person that respects the other people and their work and their property, I would never touch anything that is not mine.

**Comment by L1ND44U** [comment]
@StarbucksBG I understand what you are saying. But you are coding 18 hours a day, because you get paid.
I react for your message "Because you stay and do nothing else than waiting to make money!" These days mining cost a lot of money, rigs maintenance and people are not doing money. Just a corporation that can afford to build farm with thousands of GPU's. 
Idea to make bitcoin gold close to people that can use GPU's instead of Asics is nice. But as far I know 14gh Asics cost $1600 computer with 1x 1080 ti = $1200. Asics can make you daily $12 with GPU you will be lucky to get $3 with big dificulty and big rich farms full of GPU's are just growing. 
Where is the money Lebowski :D For sure not for small home PC owners ;-)

**Comment by StarbuckBG** [comment]
I have 2 rigs at my home. I support the idea, because that way anyone can mine. You can even use your CPU not GPU. This is decentralization. In Bulgaria we say “unity makes strength”. You cannot blame me that GPUs are expensive, you can go to the site of nVidia and AMD, and blame them. I can send you their contacts if you want.

**Comment by L1ND44U** [comment]
@starbuckBG you have 2 rigs at home. I have 3 rigs, but the rest of the population hardly saving money to get first 1080 Ti. That means Satoshis idea that everyone can mine the BTG will be violated by corporations. There is no decentralisation because big corporations have 2 floors full of GPU's and another floor full of Asics. Rather tell me what is the major change between Zcash and BTG in miner, because I need to make code for my proxies to be able mining most coursed coin in history and why it was not possible handle that change at pool node instead of modifying miner software.

**Comment by StarbuckBG** [comment]
Ok tell me what is better :
1. To have a large large BitMine that can have more of the 50% of worlds hashrate in less than a year
2. Thousands of GPU miners that already mine other crypto currencies and not enough money by a single company to own all the hashrate. 

I know a lot more persons mining with GPU than people mining with ASIC. Actually I know only 1 person that has ASIC miners. 

You cannot judge the way I think it is right. You can expose facts and provide your point of view, but I believe in the decentralization and I believe in Bitcoin as concept and implementation. I don’t like the mega mining factories that mine bitcoin and that created Bitcoin Cash.

**Comment by L1ND44U** [comment]
1. Bitmain, Innosilicon maybe another supplier of Asics. But there you have 6 farms I know and 3 big cloud mining companies selling the hash rate, my friends own few, I have 2 Asics.
2. GPU's just Nvidia or Amd that means 2 companies for Equihash is best nvidia. The prices are higher and ROI even higher comparing Asics have best ROI than GPU. Big clouds like Genesis or Farms have thousands of GPU's.
Let's speak about mining decentralisation who will run 1 GPU at home to make $3 of the farm will make bigger investment it will raise difficulty and you get $0.7 per day.

Doesn't matter if you are using Asics or GPU money are making bitmain, innosilicon,NVIDIA and Amd. 

Decentralisation of mining is nonsense big farms win and Satoshis idea that everyone can mine at home will die because no one at home will run 1x GPU to have $3 and later maybe 75 cents. Mega factories such as Nvidia, MSI will making good money.

**Comment by leto** [comment]
@StarbuckBG you said `The fact that I have decided to contribute to the projects don’t make it my job. If you contribute to the projects you will also get bounties and etc.` but we all assume that you are getting some % of the pre-mine, which is a HUGE AMOUNT OF MONEY. If you are getting 0% of the pre-mine, you should say so. And if you get some non-zero % of the pre-mine, you should make that public, too. Every BTG person should announce which % of the pre-mine they are getting, it would help clear up a LOT of mystery. In case anybody was wondering, I get 0% of the pre-mine

**Comment by StarbuckBG** [comment]
You are getting 0% because you did not finish the tasks that you have committed to. 
You see working testnet because me, H4x and few other guys stayed several days and nights to make it. Only the talks with you about the bounty for you to create a testnet (you requested 650 BTG to be exact) lasted 4 days. 
Then you committed to 300 BTG for providing working Electrum Wallet. 

This coins are coming exact from the premine. When you judge you must expose all the facts. Do not try to misinform the people, it is not correct. 

The correct sentence would be “I get 0 from the premine because I have failed these guys, twice, when they trusted and relied on me”, because we really did rely on you and we were very happy when you contacted us. However with it without you we are doing our best, sleepless nights, hard days, and whatever else, we are not giving up, and we are not failing the people who believe and rely on us.

**Comment by hardx4** [comment]
Thank you @StarbuckBG your contribution to the network will never be skewed, I am very grateful for the changes made in z-nomp, all of the team are to be congratulated, I recognize that this is not easy, it often takes hours or days of sleep!

**Comment by Airead** [comment]
@StarbuckBG Is your contribution https://github.com/poolgold/z-nomp still working? when I run `npm start`, I got `Error: Invalid checksum`.
The commit I used is `5e66e540e6b0e210c12ed4a9c01c3d9f6288f6f1` commited at `2017-11-06 00:47`

logs:

```
npm start

> z-nomp@0.0.4 start /home/office/src/bitgold-z-nomp
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js

2017-11-06 13:25:56 [POSIX]	[Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2017-11-06 13:25:56 [Master]	[CLI] CLI listening on port 17117
2017-11-06 13:25:56 [PPLNT]	[testcoin gold] TimeShare processing setup with redis (127.0.0.1:6379)
2017-11-06 13:25:56 [Master]	[PoolSpawner] Spawned 1 pool(s) on 1 thread(s)
2017-11-06 13:25:57 [Switching]	[Setup] (Thread 1) Loading last proxy state from redis
2017-11-06 13:25:57 [Pool]	[testcoin gold] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
/home/office/src/bitgold-z-nomp/node_modules/_bs58check@2.0.2@bs58check/index.js:46
  if (!payload) throw new Error('Invalid checksum')
                ^

Error: Invalid checksum
    at Object.decode (/home/office/src/bitgold-z-nomp/node_modules/_bs58check@2.0.2@bs58check/index.js:46:23)
    at Object.fromBase58Check (/home/office/src/bitgold-z-nomp/node_modules/_bitcoinjs-lib-zcash@3.0.1@bitcoinjs-lib-zcash/src/address.js:8:27)
    at Object.exports.createGeneration (/home/office/src/bitgold-z-nomp/node_modules/_stratum-pool@0.1.6@stratum-pool/lib/transactions.js:75:42)
    at new BlockTemplate (/home/office/src/bitgold-z-nomp/node_modules/_stratum-pool@0.1.6@stratum-pool/lib/blockTemplate.js:36:35)
    at JobManager.processTemplate (/home/office/src/bitgold-z-nomp/node_modules/_stratum-pool@0.1.6@stratum-pool/lib/jobManager.js:141:32)
    at /home/office/src/bitgold-z-nomp/node_modules/_stratum-pool@0.1.6@stratum-pool/lib/pool.js:586:66
    at itemFinished (/home/office/src/bitgold-z-nomp/node_modules/_stratum-pool@0.1.6@stratum-pool/lib/daemon.js:155:36)
    at /home/office/src/bitgold-z-nomp/node_modules/_stratum-pool@0.1.6@stratum-pool/lib/daemon.js:169:17
    at parseJson (/home/office/src/bitgold-z-nomp/node_modules/_stratum-pool@0.1.6@stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/office/src/bitgold-z-nomp/node_modules/_stratum-pool@0.1.6@stratum-pool/lib/daemon.js:95:17)
2017-11-06 13:25:57 [Master]	[PoolSpawner] Fork 0 died, spawning replacement worker...
```

**Comment by StarbuckBG** [comment]
Check your configuration. The addresses for the mining 
“address”:””
“taddress”:”” 
are not correct or not inputed.

Please submit these kind of issues to poolgold z-nomp repo.

**Comment by Airead** [comment]
@StarbuckBG Thanks for you reply. I want to create issue to poolgold/z-nomp, but maybe you disable its issues feature.

I rechecked your methions. Both addresses are corrected. after that, npm start still has the same error:
```
$ cat pool_configs/btg_testnet.json | grep -e \"address -e \"tAddress
    "address": "mp8nfHLyeCgdkVaD8cpFPNSkeDwm6rBCxs",
    "tAddress": "mgju5HWdwmv5KZvwXcdxsC3AbbYaUDiQU7",

$ bin/bgold-cli -testnet validateaddress mp8nfHLyeCgdkVaD8cpFPNSkeDwm6rBCxs
{
  "isvalid": true,
  "address": "mp8nfHLyeCgdkVaD8cpFPNSkeDwm6rBCxs",
  "scriptPubKey": "76a9145e87f058257ea3cdd1417afa7ad06b0c10381c2588ac",
  "ismine": true,
  "iswatchonly": false,
  "isscript": false,
  "pubkey": "02229c1433220baa3e58217a5b4a25284bb0997d78c310d065b11c871426876d59",
  "iscompressed": true,
  "account": "",
  "timestamp": 1509593726,
  "hdkeypath": "m/0'/0'/0'",
  "hdmasterkeyid": "9993145c4370359b4d8fe16754e7ea5e4fac08be"
}

$ bin/bgold-cli -testnet validateaddress mgju5HWdwmv5KZvwXcdxsC3AbbYaUDiQU7
{
  "isvalid": true,
  "address": "mgju5HWdwmv5KZvwXcdxsC3AbbYaUDiQU7",
  "scriptPubKey": "76a9140d6ad861e278df1fb690009e0cfb42942474ac5888ac",
  "ismine": true,
  "iswatchonly": false,
  "isscript": false,
  "pubkey": "029dff4b71702d483532ce81f2a18721d214bd34851d7e70557d0e3cd96f3bd230",
  "iscompressed": true,
  "account": "",
  "timestamp": 1509593726,
  "hdkeypath": "m/0'/0'/1'",
  "hdmasterkeyid": "9993145c4370359b4d8fe16754e7ea5e4fac08be"
}
```

**Comment by StarbuckBG** [comment]
Create issue there I will have a look, thanks!

**Comment by leto** [comment]
@StarbuckBG I didn't fail you, I didn't want to write you *invaluable* code so you could pay me in a currency that doesn't exist, that you didn't even grasp how to launch, lol. I couldn't even begin to work on Electrum support without a functioning testnet, or BTG address format stuff, but you didn't even know what a testnet was when you were selling the world on BTG :+1:

You still do not say, how much does @h4x3rotab , how much does @StarbuckBG and how much does Jack Liang get of the pre-mine? You didn't even grasp, I was clarifying to the rest of the world that I got 0%, because I need to distance my good name from your quackery. I want people to know that I am not associated with this scammery that you call a Bitcoin fork.

**Comment by L1ND44U** [comment]
@Leto agree with you. ❤️👍

**Comment by StarbuckBG** [comment]
Let’s just stop here. I respect you as a developer, you do awesome things, you have a lot of knowledge and cool projects. My personal opinion for you, as a person is not that good, so I will keep it for me. You have personally insulted me, based on your own opinion, you have told in public that I’m terrible developer and that I know nothing about crypto currencies, that I have no idea how the crypto network works and that I will not be able to make a testnet. Well, testnet is running perfectly (: 
We’ve got a lot of conversation, a lot things that can be shown in public, about the way you treat the project before you have taken the task for the Electrum and after that. Personally I feel disappointed about everything that happened with you and I regret the fact that I have contacted you for opinion 3 weeks ago.

PS. This is not the full conversation from that moment, because it is over 200 messages.
